<Project Sdk="Dalamud.NET.Sdk/13.1.0">
  <PropertyGroup>
    <Version>0.1.1</Version>
    <AssemblyName>MarketBoardCollector</AssemblyName>
    <RootNamespace>MarketBoardCollector</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
